#!/bin/bash
# 256c.sh: Display all 256 colors & backgrounds.
for fgbg in 38 48 ; do 
  for color in {0..255} ; do
    printf "\e[${fgbg};5;%sm  %3s \e[0m" $color $color
    if [ $((($color + 1) % 8)) == 4 ] ; then
      echo
    fi
  done
  echo
done


###########################
# Prints things in color  #
###########################
# printcf - eventually delete as it's now redundant
printcf() {
# Sets the colors.
    case $1 in
       "red") tput setaf 88;;
       "green") tput setaf 22;;
       "orange") tput setaf 166;;
       "blue") tput setaf 17;;
       "purple") tput setaf 97;;
       "cyan") tput setaf 75;;
       "gray" | "grey") tput setaf 245;;
       "lgray" | "lgrey") tput setaf 251;;
    esac
# Prints 2nd argument in the color
    printf "$2";
# Optional new line -- anything following the 2nd argument will trigger it
    [[ ! -z "$3" ]] && echo 
# Resets the color
    tput sgr0
}
